---

- name: ensure directory for htpasswd credentials are exists
  file:
    state: directory
    path: "{{ htpasswd_credentials_path }}"
    mode: 0755

- name: ensure htpasswd credentials are configured.
  community.general.htpasswd:
    name: "{{ item.1.username }}"
    password: "{{ item.1.password }}"
    state: "{{ item.1.state | default('present') }}"
    path: "{{ item.0.path }}"
    owner: "{{ item.0.owner | default(omit) }}"
    group: "{{ item.0.group | default(omit) }}"
    mode: "{{ item.0.mode | default('u=rw,g=r,o-r') }}"
    crypt_scheme: "{{ item.1.crypt_scheme | default(omit) }}"
  with_subelements:
    - "{{ htpasswd_credentials }}"
    - users
  loop_control:
    label: "{{ item.0.path }} : {{ item.1.username }}"
  # no_log: true
  register: added_users

- name: Reporting changes
  debug:
    msg: "{{ added_users.results | selectattr('changed', 'equalto', True) | map(attribute='msg') | list }}"
  when:
    - htpasswd_list_users

...
