---

- name: ensure directory for htpasswd credentials are exists
  file:
    state: directory
    path: "{{ item.value.path | dirname }}"
    owner: "{{ item.value.owner | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: 0755
  loop: "{{ htpasswd_credentials | dict2items }}"
  loop_control:
    label: "{{ item.value.path | dirname }}"

- name: ensure htpasswd credentials are configured.
  htpasswd:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    path: "{{ item.value.path }}"
    owner: "{{ item.value.owner | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
    mode: "{{ item.value.mode | default('0644') }}"
    crypt_scheme: "{{ item.value.crypt_scheme | default(omit) }}"
  loop: "{{ htpasswd_credentials | dict2items }}"
  loop_control:
    label: "{{ item.value.path }} - {{ item.key }}"
  no_log: true
  register: added_users

- name: Reporting changes
  debug:
    msg: "{{ added_users.results | selectattr('changed', 'equalto', True) | map(attribute='msg') | list }}"
  when:
    - htpasswd_list_users

...
