---

- name: include OS specific configuration
  ansible.builtin.include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      paths:
        - "vars"
      files:
        # eg. debian-10 / ubuntu-20.04 / centos-8 / oraclelinux-8
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}.yml"
        # eg. archlinux-systemd / archlinux-openrc
        - "{{ ansible_distribution | lower }}-{{ ansible_service_mgr | lower }}.yml"
        # eg. debian / ubuntu / centos / oraclelinux
        - "{{ ansible_distribution | lower }}.yml"
        # eg. redhat / debian / archlinux
        - "{{ ansible_os_family | lower }}.yml"
        # artixlinux
        - "{{ ansible_os_family | lower | replace(' ', '') }}.yml"
        - default.yml
      skip: true

- name: redhat support
  when:
    - ansible_os_family | lower == 'redhat'
  block:
    - name: import EPEL GPG key
      ansible.builtin.rpm_key:
        key: https://archive.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        state: present

    - name: install EPEL repository
      ansible.builtin.yum_repository:
        name: epel
        state: present
        description: Extra Packages for Enterprise Linux {{ ansible_distribution_major_version }} - $basearch
        baseurl: http://download.fedoraproject.org/pub/epel/{{ ansible_distribution_major_version }}/$basearch
        gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
        metalink: https://mirrors.fedoraproject.org/metalink?repo=epel-{{
          ansible_distribution_major_version }}&arch=$basearch&infra=$infra&content=$contentdir
        failovermethod: priority
        gpgcheck: 1
        enabled: 1

- name: validate htpasswd data
  ansible.builtin.set_fact:
    validated_credentials: "{{ htpasswd_credentials | validate }}"
  no_log: true

- name: inform about non-valid data
  ansible.builtin.debug:
    msg: "{{ validated_credentials.non_valid_msg }}"
  when:
    - validated_credentials.non_valid_msg is defined
    - validated_credentials.non_valid_msg | count > 0

- name: re-define htpasswd_credentials
  ansible.builtin.set_fact:
    htpasswd_credentials: "{{ validated_credentials.valid_entries }}"
  no_log: true

...
