---

# nginx_remove_default_vhost: true

nginx_vhosts:
  - listen: "80"
    server_name: "htpassword.test"
    root: "/var/www/html"
    index: index.html
    filename: "htpassword.test.conf"

    extra_parameters: |
      location / {
        auth_basic           "Administrator’s Area";
        auth_basic_user_file /etc/nginx/.admin-passwdfile;
      }

...
