---

#ansible_python_interpreter: python3

htpasswd_credentials:

  - path: "{{ htpasswd_credentials_path }}/.admin-passwdfile"
    users:
    - username: admin
      password: ZRhgqhaAjdbuFXj2PLJTzYy5PrRsStNaeYWd9c3Ze3
    - username: administrator
      password: gp!tk<r+JcDyJhV5!tgzZVUWx233HLVZMJUy<YNVPZ
      crypt_scheme: apr_md5_crypt

  - path: "{{ htpasswd_credentials_path }}/.administrator-passwdfile"
    users:
    - username: administrator
      password: gp!tk<r+JcDyJhV5!tgzZVUWx233HLVZMJUy<YNVPZ
      path: /etc/nginx/.administrator-passwdfile
      crypt_scheme: apr_md5_crypt

...
